version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - express-server

  express-server:
    build:
      context: .
      dockerfile: ./src/proxy/Dockerfile
    ports:
      - '3001:3001'
