version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOCKIDAR_USEPOLLING=true
    depends_on:
      - express-server

  express-server:
    build:
      context: .
      dockerfile: ./src/proxy/Dockerfile
    volumes:
      - './src/proxy:/usr/src/app'
    ports:
      - '3001:3001'
